### PR TITLE
Improve usage guide

### PR DESCRIPTION
**Pull request by tomas-mota**
Signed-off-by: tomas-mota <tomasrebelomota@gmail.com>
### Description of your changes

As a beginner, without following [this video](https://www.youtube.com/watch?v=EN_vqJivZrk) I would have absolutely no clue on how to use this template. Hopefully these additions (and any further suggestions) will help other newcomers with getting started.

### CODE REVIEW

**Review by ytsarev — APPROVED** [review]
Thank you so much, these directions look very actionable and clear 👍

**Comment by tomas-mota** [comment]
Thank you. 
Perhaps someone else can try this out, but for me `make lint`, which is ran as part of `make reviewable` is not working, which I think has to do with updating to go 1.19. 

When I set https://github.com/upbound/build/blob/ba699a88514e938206a63291d6d64b3f7c369de6/makelib/golang.mk#L99 to 1.50 (latest) it works (with some deprecation warnings). Should the version in the build submodule perhaps be bumped?

**Comment by ytsarev** [comment]
sure, feel free to open PR to https://github.com/upbound/build

**Review by muvaf — APPROVED** [review]
Thank you!

**Pull request merged**
